### PR TITLE
feat(execution-timestamps)

### PR DESCRIPTION
**Pull request by caviri**
Added real timestamp for executions.

### CODE REVIEW

**Review by sabinem — CHANGES_REQUESTED** [review]
**fix** I think  to be consistent we should add the timestamps also on the steps. They also have a `start_timestamp` and `end_timestamp`.

**suggestion**:
Additionally the steps have a `timestamp` field whereas the execution do not. I would add would add a `timestamp` field also on the execution and set it to the time when the execution was created.  

**suggestion**

**Comment by sabinem** [comment]
@caviri yes sounds good to me: watch out when renaming the timestamp field on where in the code it is used.

**Comment by caviri** [comment]
Hi @sabinem, here you have the PR adding the `start_timestamp` at the beginning of the step.

**Comment by caviri** [comment]
Hello @sabinem, I added the timestamps on the orchestrator. This is only valid when the steps are running ephemeral components.

**Review by sabinem — APPROVED** [review]
@caviri Looks good to me: ready to merge

**Pull request merged**
