### PR TITLE
Release0.3.0

### PR DESCRIPTION
**Pull request by sabinem**
Relase 0.3.0:

Status of bug fixes and comments: 

- [x] 1. Home page: aligned elements and tried to improve on the content
- [x] 2. Menu Bar: removed "run" from the navigation: then it makes no longer sense to select the execution on the run page. Therefore it is now selected on the execution page and the user accesses the run page with an already selected execution. This also makes the run page easier to understand.
- [x] 3. User: The user is now able to add a new directory as work directory on the user page
- [x] 4. General Layout: the general layout is now changed and the workarea has been integrated into the page
- [x] 5. Components: the component page has now the select tab renamed to component options where a component can be selected and versions can be added
- [x] 6. Manage Executions > Select and Execution: the button to unselect an execution has been renamed as suggested
- [x] 7. Manage Executions > Select Execution: new line on the parameter form and ports fields have been renamed as suggested. A check mark has been added to indicated that a parameter file was uploaded
- [x] 8. Manage Executions > Sidebar (Work Area): the workarea information has been added for the execution
- [x] 9 Prepare and Run Executions: Enter secrets manually: this was postponed to the next release, see comment below and the other button I don't want to rename it since it does not open the logging but really just show the output folder. 
- [x] 10. Prepare and Run Executions: The behavoiur of the run button is correct, it just sometimes takes a lot of time until something happens.

### CODE REVIEW

**Comment by caviri** [comment]
Hello @sabinem, I'm building and testing the ODTP GUI on my Windows machine. 

 I'm going to list here my suggestions and bugs I'm catching: 

1. Home. 

image

`Check out documentation` appears misplaced to the right. I would be more coherent to put if below. Also. I would add a little and concise list of the steps that are needed based on the most common cases. But this last is not urgent. 

2. Menu bar. 

A `run` is one action related to execution, so it would be better to include it within executions. If we want a shortcut, we can add a link to the section within Executions. 

3. Users

image

How feasible is adding a button to create a new folder when setting the working directory?

4. General Layout. 

The sidebar with the working area and other information is on the right, which feels a bit strange. Did you test the feeling of placing this to the right? 

Also, this sidebar disappears when the screen width is minimized. 


5. Components.

In the tabs menu, `Add version` at the same level of `Add component`. Add version should be a submenu under component selection. I would rename `Select Component` to `Component options` or `Component settings` and add the option to add a new version in that tab. 


6. Manage Executions > Select and Execution

Change `Cancel execution selection` to `Unselect execution`. 

7. Manage Executions > Select Execution

Amazing way of adding steps to the workflow. Great work @sabinem!! 

Regarding the parameters from files, is there any way to change the icon or the color once you pick the parameters?

Parameters overwriting: Change `Add/Remove line` by `Add/Remove parameter`. 

Ports. Change `Ports` to `Ports mapping (XXXX:XXXX)`

8. Manage Executions > Sidebar (Work Area)

Missing `work directory` information. 

9. Prepare and Run Executions

Add the possibility to add secret fields. This is fine if the users needs it. However, make them "star" coded? Like `***********`

I'm currently running the whole corsica pipeline. But Amazing work Sabine!

**Comment by sabinem** [comment]
@caviri I want to discuss with you on 

> 9. Prepare and Run Executions
Add the possibility to add secret fields. This is fine if the users needs it. However, make them "star" coded? Like ***********

I would like to postpone this, unless you help me solve the problem I have with this: 

- for the parameters there is no problem to overwrite them, as they are stored as variables in the mongodb and taken from there in CLI command `odtp execution run --project-path /Users/smaennel/odtp/digital-twins/testagain --execution-id 665447b2d8e14289615ef5a7 --secrets-files file.txt` 

But the secrets are taken from file. And the GUI starts the CLI command. Otherwise I would have to call the WorkflowManager directly, but it a long running process and should rather run in the background, therefore I went with starting the CLI command.

To be able to overwrite secrets, the CLI command would have to be changed, so that is not only takes files but also variables. 

I would suggest to leave it as it is for now, since it is possible to provide secrets, you just have to add them via files. 
What do you think or suggest? It would be for sure a lot of work if we want to implement the feature that you suggest here.

**Comment by caviri** [comment]
Hello @sabinem, 

I think it's fine for this release. So there's no problem. I can adapt the CLI on the 0.4.0 to receive secrets and parameters as individual flags (In a similar way to docker CLI) `-p` and `-s`. This should pave the way for the implementation on the GUI.

**Review by caviri — CHANGES_REQUESTED** [review]
Hello @sabinem, I tested it and it works fine with the corsica example. 

Just a couple of things: 
- When running `odtp --version` it doesn't print out 0.3.0
- Line 27 of `.env.dist.local` is missing an `=` after the variable. 

Ready to release. Great work!

**Comment by caviri** [comment]
Hello @sabinem, thank you! Can we have a two docker compose? One for dev and the other for "production"? It can happen that some users might change the branch on local potentially affecting to the files located on the docker, so I think it's better to reduce the amount of volumes mounted. What do you think?

**Comment by sabinem** [comment]
@caviri We added a setting that decides whether the code base will be editable. Hope this is considered by you good enough to take care of your concern on not having the code base editable in production.

**Comment by caviri** [comment]
Good morning @sabinem, not fully convinced. What would be the point of having then an `/app` volume mounted. My concern wasn't about the `--editable` flag, which I think it can remains. But rather with the `/app` volume mounted.

**Comment by sabinem** [comment]
@caviri Okay I can do that: but even then you would be against mounting the the app folder in the dev setup?

**Comment by caviri** [comment]
Hi, no, I think that it’s a good idea for developers. I was just worried about non experts users.

**Review by caviri — APPROVED** [review]

**Pull request merged**
